### ISSUE TITLE
Allow users to specify a browser to open an app in

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-cli#102]
Currently, `skyux serve` opens the application in the user's default browser. This change would allow for the user to specify an alternative browser to open the application in. This is useful for cross-browser manual testing as, without this option, the user has to change their default browser in order to launch into another browser.

**Comment by Blackbaud-PatrickOFriel** [comment]
Now lives in https://github.com/blackbaud/skyux2/issues/402
