### ISSUE TITLE
Research Firefox localhost exception

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-cli#103]
Whenever you try to launch an application into Firefox the application just hangs and never loads. In order to fix this you must navigate to the `localhost` url and then follow the instructions for adding an exception for the localhost url. The warning that is shown when navigating to the `localhost` url is that the connection is not secure. After this is done, the application can launch at the `sky.blackbaud-dev.com` url. We should research whether or not we can configure things so that this exception is not needed and if this is not possible then we should document that this is required when using Firefox.

**Comment by Blackbaud-PatrickOFriel** [comment]
Now lives at https://github.com/blackbaud/skyux2/issues/401
