### ISSUE TITLE
Support building skyux-builder in Windows

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-cli#108]
@Blackbaud-JonathanBell and I ran through some issues to make `skyux-builder` easier to test in Windows.

- `npm run coverage` should follow https://github.com/gotwarlost/istanbul#usage-on-windows
- `npm run lint` throws errors about invalid line endings.  My guess is this is related to not having a `.gitattributes` file.
- Failing unit test because of forward vs back slash "should support a custom routesPattern"

**Comment by Blackbaud-PatrickOFriel** [comment]
Now lives in https://github.com/blackbaud/skyux2/issues/400
