### ISSUE TITLE
Serve all JS files from the same folder

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux-cli#19]
When we generate vendor/polyfills/app/skyux.js files there is a high probability many of these files will be the same across SPAs.  Right now we serve them all from the same subdirectory as the SPA, but since the file names include hashes that reflect the file's content we should be able to serve them up from the same subdirectory regardless of SPA without fear of clashes.

**Comment by Blackbaud-TerryHelems** [comment]
Copied to https://blackbaud.visualstudio.com/Products/_workitems/edit/715366
