### ISSUE TITLE
Consider better wording for SPA root directory prompt

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux-cli#30]
The "What is the root directory for your SPA?" prompt could use some more information about how the value specified here will be the root directory in SKY Pages Host and that a local folder with a prefix of "sky-pages-spa-" will be created with it.

**Comment by Blackbaud-PatrickOFriel** [comment]
Now lives in https://github.com/blackbaud/skyux2/issues/421
