### ISSUE TITLE
Getting started documentation for Sky UX Builder

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux-cli#41]
Start creating documentation for the functionality and specific options for SKY Pages. (Getting started using SKY Pages, using easy mode, how routing works, etc)

Initially this can be placed in the Readme for the sky-pages-cli repository and later we can create a documentation site like [SKY UX](skyux.developer.blackbaud.com)

**Comment by blackbaud-johnly** [comment]
Initial getting-started docs in place after https://github.com/blackbaud/skyux2/pull/346.
