### ISSUE TITLE
Monitoring Alerts

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-cli#45]
We should add monitoring alerts to our host site.

**Comment by Blackbaud-BobbyEarl** [comment]
Clarifying this poorly worded issue...  Once the host has been deployed to it's production home, be sure to enable alerts, mirroring what we've done with our other production environments.

**Comment by Blackbaud-TerryHelems** [comment]
This will be accomplished in conjunction with integrating with Team Upsilon's Azure automation.
