### ISSUE TITLE
Add ability to override default route configuration

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux-cli#5]
When we generate routes based on the file system we need to allow the consumer to specify overrides for the generated route, such as `canActivateRoute` which will be SPA-specific.

**Comment by blackbaud-brandonstirnaman** [comment]
Don't forget about `canActivateChild` 👍

**Comment by Blackbaud-PatrickOFriel** [comment]
Now lives in https://github.com/blackbaud/skyux2/issues/423
