### ISSUE TITLE
Disallow host from being included in frame

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-cli#50]

**Comment by Blackbaud-TerryHelems** [comment]
Add header "X-Frame-Options" = "DENY"

**Comment by Blackbaud-PaulCrowder** [comment]
This should probably be an option that maybe defaults to `DENY` but can be overridden via configuration.  We will want to allow host to be included in an iframe in cases such as an Office add-in.

**Comment by Blackbaud-TerryHelems** [comment]
Copied to https://blackbaud.visualstudio.com/Products/_workitems/edit/715359
