### ISSUE TITLE
Add template + component creation to cli

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-cli#56]
I like ng-cli's ability to create components, routes, etc.  I think we can add value to that by allowing our consumers to create pages with the necessary template + components.  Something like `skyux create-page list` (see http://skyux.developer.blackbaud.com/guidelines/page-layouts/).

**Comment by Blackbaud-PatrickOFriel** [comment]
Now lives in https://github.com/blackbaud/skyux2/issues/419
