### ISSUE TITLE
Run e2e tests against the AOT build

### ISSUE THREAD

**Issue by Blackbaud-JonathanBell** [blackbaud/skyux-cli#76]
The tests will run a lot faster if they execute against AOT and it would be more appropriate to test that version.

**Comment by Blackbaud-BobbyEarl** [comment]
Completed via [skyux-builder@1.0.0-beta.10](https://github.com/blackbaud/skyux-builder/blob/master/CHANGELOG.md#100-beta10-2017-02-13)
