### ISSUE TITLE
Navbar component - submenu target area

### ISSUE THREAD

**Issue by Blackbaud-JonathanBell** [blackbaud/skyux-cli#78]
When hovering over a submenu item in the nav bar, mouse over any part of the menu will highlight the menu item you are hovering on.  However, if you are not over (or nearly over) the actual text, then the link doesn't work.  Hovering the text makes the font bold, but hovering the div still highlights the div.  Clicking the div closes the nav menu but doesn't navigate.

This means the touch target for the menu item is much smaller and it is misleading/confusing because you see a hover state that doesn't do anything.  Also, the top-level menu items have a touch target of the whole div/button area and not just the text.

https://developer.blackbaud.com/skyux2/components/navbar

![image](https://cloud.githubusercontent.com/assets/11995039/22426565/b47cf0aa-e6cd-11e6-834f-ef45cd269b4a.png)

**Comment by Blackbaud-PaulCrowder** [comment]
This bug should be filed on the https://github.com/blackbaud/skyux2 repo.
