### ISSUE TITLE
Combine skyux2 and skyux-builder repos.

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-cli#85]
After further discussion and watching how user's consume us, we think combining the skyux2 component library and the skyux-builder code might be more efficient and beneficial.

**Comment by Blackbaud-PatrickOFriel** [comment]
Does this include the cli repo as well?

**Comment by Blackbaud-BobbyEarl** [comment]
The skyux-cli would remain separate.  It's installed globally which means consumer are less likely to update it (even with the auto prompts to upgrade we implemented).  Keeping that in mind means we want to keep it as lightweight as possible and contain as little logic as possible.

It performs two basic functions:

- Globally register `skyux` as a known command.
- Handle the commands that can be run outside the context of a project: `skyux help` and `skyux new`

**Comment by Blackbaud-PatrickOFriel** [comment]
Well, when we do this work, we might want to think about taking the opportunity to combine all of our issues into the SKY UX 2 repository instead of having some in skyux-cli. We've had at least one case of a consumer filing an issue in the wrong place, and this might help solve some of the confusion.

**Comment by Blackbaud-BobbyEarl** [comment]
Great suggestion @Blackbaud-PatrickOFriel!

**Comment by Blackbaud-BobbyEarl** [comment]
I think we should reconsider the priority of this request, stack-rank it if you will.

The confusion around issues.  The inability to update shared dependencies (angular modules) without coordination between builder & skyux2.  The fact that all current skyux apps will need to have their package.json files updated to only point to one package.  

These are just a few of the reasons I think it has a higher priority.  I believe the build process orchestration will be the most challenging part to merge between the two code bases, especially without negatively affecting performance (build time) or test coverage.

Perhaps as a first past, we could leave the repos/packages separate, but at least have builder require skyux2 (or vice-versa) and remove that requirement in the current skyux-template.

Thoughts @Blackbaud-PatrickOFriel and @Blackbaud-PaulCrowder?

**Comment by Blackbaud-BobbyEarl** [comment]
Possible complications to the "quick" approach we discussed today.  Even if we took the first approach of removing skyux-builder from the template, and moved it as a dependency for skyux, we'd have to update CLI to either not look in package.json or look for skyux instead.

**Comment by Blackbaud-PatrickOFriel** [comment]
Do you see that as a blocker to doing that this week?

**Comment by Blackbaud-PatrickOFriel** [comment]
Now lives in https://github.com/blackbaud/skyux2/issues/410
